Addon store
BetterDiscord/BetterDiscord pull request #1193
Opened 2022-01-30 19:00 UTC by Tropix126

@Strencher decided to fix some of the work he and I did earlier last year. This is still somewhat work-in-progress, but is fairly stable and fully functional.

Current todos:
- Finish (or temporarily remove) store page styling.

2022-01-30 19:02 UTC, Tropix126 commented
I'm not completely familliar with how i18n works internally, but i've changed some of the blankstate strings in English. From a quick sweep it looks like to get rid of outdated or mark unfinished strings, you just replace it with a blank one (`""`), so I've done that. Let me know if that needs changing/a revert.

2022-01-30 21:49 UTC, dav1312 commented
Editing plugins/themes on a detached window opens the file in the system editor

2022-01-31 15:57 UTC, Tropix126 commented
> When you click on an addon to see the readme, there isn't really a way to go back. And if you press "installed" and then "store" to go back to the store, all tags are gone.

Aware of this. Store pages are unfinished and will be rewritten in the near future.

2022-01-31 16:16 UTC, TheGreenPig commented
> Once finished, store pages will likely resemble the pages seen [here](https://store.betterdiscord.app/themes).
Just visited this site and it looks good, but maybe 0.1m could be changed to 100k? It's rather inaccurate and not really pretty to have values below 1 in my opinion.

2022-01-31 17:26 UTC, Tropix126 commented
> > Once finished, store pages will likely resemble the pages seen [here](https://store.betterdiscord.app/themes).
> 
> Just visited this site and it looks good, but maybe 0.1m could be changed to 100k? It's rather inaccurate and not really pretty to have values below 1 in my opinion.

This site is rather old. I worked on it shortly after the initial release of the site. It's very rough around the edges and is not used anywhere in this PR. AFAIK we use a different method of abbreviating stats in the actual store. All I plan to borrow is the rough idea of its design.

2022-02-03 12:45 UTC, dav1312 commented
Not directly related to the store but a small idea for the changelog banner for when it's added?
Using https://nyri4.github.io/Discolored/assets/empty.svg
![store](https://user-images.githubusercontent.com/63931154/152344957-ce757fb6-fc35-4d61-85fd-026e745b63be.png)

2022-02-23 09:07 UTC, TheGreenPig commented
Some things I noticed:

- Clicking the card throws a `this.props.onDetailsView is not a function` error. (Probably just not implemented yet, I thought I'd mention it here anyway, I think the plan is to show the README there?)
- Maybe a "Do not show this again" checkbox could be added to the popout that get's shown after you press the install button? The popup is nice, but it might get annoying every time you want to install an addon... the other option I think would be good is not display the info when clicking the install button, but adding an "info" button that will display the popout instead. 
- Just an idea, but maybe the install button could turn into a red uninstall button if the addon is installed already, instead of making the button disabled? If you want to test out a theme for example and you try it, but decide you don't like it right away, it's easier to have a button there to uninstall it instead of having to go to the other tab, find the theme and delete it there...
- How about being able to filter by multiple tags?
- Not sure if I'm missing the feature, but maybe the support server invite could be added in the info popoup (or as it's own icon) as well? It looks like guild data is already passed in the addon props I think, so maybe you're already planning to do so...
- I think you can sort by "Date added", but not actually view when it was added anywhere? The info popoup shouldn't be bloated with information for sure, but still, I feel like if you can sort by "Date added" you should be able to view that data as well...

So I obviously don't know what you're future plans are/if you have considered or will implement the things I listed above/even want feedback at all, but maybe this is still useful feedback...

2022-02-23 15:00 UTC, Strencher commented
> Clicking the card throws a this.props.onDetailsView is not a function error [...[

Yes, this is because the store was disabled temporarily due to crashes.

> Maybe a "Do not show this again" [...]

That's a good idea. But although I'd rather make it a feature such as holding shift to install immediately. I'll add it to the todo.

> - Just an idea, but maybe the install button could turn into a red uninstall button if the addon is installed already [...]
> - How about being able to filter by multiple tags?
> - I think you can sort by "Date added", but not actually view when it was added anywhere? [...]

Yes. I can out in on our todo list.

2022-02-24 07:58 UTC, TheGreenPig commented
A setting to automatically enable the addon after it was downloaded would also be nice...

2022-03-08 16:13 UTC, Tropix126 commented
> I think you can sort by "Date added", but not actually view when it was added anywhere? The info popoup shouldn't be bloated with information for sure, but still, I feel like if you can sort by "Date added" you should be able to view that data as well...

This is now shown on installation modals. Additionally, addons uploaded less than 3 months ago will get a new badge.

2022-03-19 12:07 UTC, QbDesu requested changes
The rest seems to work for me on Linux without issues.

One thing I found really weird was that installed items aren't automatically enabled. I don't see any situation where you would install something from the store and not wanna enable it right away, and if it stays like this I imagine we get a lot of people asking why the addon they just installed isn't working in #support chat. So I'm with GreenPig on that one

The only other nitpick I have concerns the design of the store cards. I think there should be some sort of shadow around them to not have the thumbnail for the theme/plugin blend into the background if the background color is the same:
![image](https://user-images.githubusercontent.com/5641607/159120242-949a5b27-6098-4cfd-82be-2b555b2049f0.png)

2022-03-19 12:11 UTC, QbDesu commented on renderer/src/ui/icons/index.js
> +export {default as Clock} from "./CLock.jsx";
This is probably just a small oversight because it won't cause any issues on Windows but Linux and Mac have case sensistive filesystems so that doesn't compile.
(forgot to actually submit that alongside my earlier comment)

2022-03-19 14:41 UTC, TheGreenPig commented
I made a mock-up how filtering for multiple tags could look like (I can provide the way I coded it if needed)

https://user-images.githubusercontent.com/67547385/159125248-1aed4d96-8164-4771-8fba-be3895c22ce6.mp4

Next to the auto-enable feature like Qb and I mentioned, another feature I think could be nice is sorting by “installed”. Should be relatively easy to implement, and it makes it easier to discover new addons you don't have yet. 

I think a share button for addons would be helpful as well (Although I'm assuming you're already planning to add something like this, since there is the addon embed feature now).

2022-03-19 15:23 UTC, Tropix126 commented
I think that i'll include an option to automatically enable, although I don't want it to be on by default. Mainly because if someone is just browsing around for themes, the rule clashes can essentially render the client unusable unless they manually clear their addon folder.

2022-03-19 15:27 UTC, Tropix126 commented
> I think a share button for addons would be helpful as well (Although I'm assuming you're already planning to add something like this, since there is the addon embed feature now).

Correct, but this likely won't be included in the initial store release since it's planned to be added into addon detail pages.

2022-03-19 16:55 UTC, Tropix126 commented
> Next to the auto-enable feature like Qb and I mentioned, another feature I think could be nice is sorting by “installed”. Should be relatively easy to implement, and it makes it easier to discover new addons you don't have yet.

How would you expect this to work? Should it _only_ show installed addons, or should it prioritize them first. If it prioritizes them first, how should the remaining addons be filtered?

I'm a bit on the nose about implementing this too, considering that the installed tab pretty much serves this purpose.

2022-03-19 18:08 UTC, TheGreenPig commented
> How would you expect this to work? Should it only show installed addons, or should it prioritize them first. If it prioritizes them first, how should the remaining addons be filtered?

Well the easiest solution would probably be to just add it in the "Sort by" section under Name, Likes etc. it's counterintuitive if one of the options is a filter and the other ones sorting options. 
So because of that, I'd say it should just prioritize the addons that aren't installed yet, but still display the addons that are installed. 

If it should be an actual filter that doesn't display addons that are installed already, it would probably need its own toggle/section/whatever, just to avoid confusion…

> I'm a bit on the nose about implementing this too, considering that the installed tab pretty much serves this purpose. 

When you're browsing for new addons to try out (and that's kind of the whole point of the store, right?), you might not want to see addons that you have already. I thought of it more like a way of discovering _new_ addons in the sense that you don't have them already. 
It's not exactly a necessary feature, I think, but it wouldn't hurt to add it?

2022-03-21 01:56 UTC, Tropix126 commented on renderer/src/ui/icons/index.js
> +export {default as Clock} from "./CLock.jsx";
Believe this should be fixed now.

2022-03-23 20:51 UTC, Tropix126 commented
Mockup for details view I made earlier.

2022-04-10 00:12 UTC, dav1312 commented
It doesn't work after removing the tempfix ([296684b](https://github.com/BetterDiscord/BetterDiscord/pull/1193/commits/296684b6b7a15039daf5e449b197c9bcc5c8bfd8))

2022-04-10 12:59 UTC, QbDesu commented
yeah, try without catch isn't valid syntax, maybe he wanted to also remove the surrounding try

2022-04-10 13:02 UTC, Strencher commented
> yeah, try without catch isn't valid syntax, maybe he wanted to also remove the surrounding try

Doesn't necessarily have to be `catch` directly, it can also be `finally`.

2022-04-11 14:25 UTC, Tropix126 commented
My mistake, just meant to revert it to how it was before. The fix itself was for a case where BD could sometimes silently fail to load if there were development errors, i'll probably throw it into a future pull, since it was committed on accident.

2022-05-24 21:26 UTC, dav1312 commented
It doesn't work after [95ccea8](https://github.com/BetterDiscord/BetterDiscord/pull/1193/commits/95ccea8e0312fed6440d55bb349391fffa1d7ad9)

2022-05-24 22:28 UTC, Tropix126 commented
> It doesn't work after [95ccea8](https://github.com/BetterDiscord/BetterDiscord/pull/1193/commits/95ccea8e0312fed6440d55bb349391fffa1d7ad9)

Fixed, turns out the `ProvidePlugin` was "providing" the react import to a single file that didn't import react lol.

2022-08-09 06:28 UTC, dav1312 reviewed
```
ERROR in ./src/styles/index.css
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
SyntaxError

(431:5) postcss-csso: /home/runner/work/BetterDiscord-App/BetterDiscord-App/renderer/src/styles/ui/store.css Identifier is expected

  429 | .theme-light .bd-store-tags span.selected {
  430 |     background-color: var(--brand-experiment, hsl(235, calc(var(--saturation-factor, 1) * 85.6%), 64.7%));;
> 431 |     color: #fff;
      |     ^
  432 | }
  433 | 
  ```

2022-08-09 06:28 UTC, dav1312 commented on renderer/src/styles/ui/store.css
> +    background-color: var(--brand-experiment, hsl(235, calc(var(--saturation-factor, 1) * 85.6%), 64.7%));;
Double semicolon

2022-08-09 06:28 UTC, dav1312 commented on renderer/src/styles/ui/store.css
> +    background-color: var(--brand-experiment, hsl(235, calc(var(--saturation-factor, 1) * 85.6%), 64.7%));;
Double semicolon

2022-08-09 06:28 UTC, dav1312 commented on renderer/src/styles/ui/store.css
> +    background-color: var(--brand-experiment, hsl(235, calc(var(--saturation-factor, 1) * 85.6%), 64.7%));;
Double semicolon

2022-08-09 06:28 UTC, dav1312 commented on renderer/src/ui/modals.js
> +    static get MaskedLink() {return WebpackModules.getModule(m => m?.default?.type?.toString()?.includes('default.MASKED_LINK'));;}
Double semicolon

2022-08-31 16:35 UTC, rauenzi requested changes
Couple minor things/changes but otherwise LGTM

2022-08-31 16:35 UTC, rauenzi commented on renderer/src/modules/addonmanager.js
> +        if (!Settings.get("settings", "addons", "autoReload")) this.unloadAddon(addon);
This setting was removed in the meantime

2022-08-31 16:35 UTC, rauenzi commented on renderer/src/modules/addonmanager.js
> +        if (Settings.get("settings", "addons", "autoEnable")) Events.on(`${this.prefix}-loaded`, enable);
this setting was removed

2022-08-31 16:35 UTC, rauenzi commented on renderer/src/styles/ui/markdown.css
> +
erm... what's up with this almost empty file?

2022-08-31 16:35 UTC, rauenzi commented on renderer/src/ui/addonerrormodal.jsx
> +                <TabBar items={tabs.map(({id, name}) => ({value: id, name}))} value={selectedTab.id} onChange={value => this.switchToTab(value)} />
Will these changes conflict with your other PR?

2022-08-31 16:35 UTC, rauenzi commented on renderer/src/ui/settings.js
> +            title,
Can you just inline these if you're going this route? i.e. `{title, addonList, addonState}` instead of multiline

2022-08-31 16:35 UTC, rauenzi commented on renderer/src/modules/bdwebapi.js
> +export default new class BdWebApi {
Idk why but I don't love the name `BdWebApi` but I also don't know of a better one... maybe just `WebAPI`? Since it's included in BD the BD part is implicit?

2022-08-31 18:41 UTC, Inve1951 commented on renderer/src/modules/bdwebapi.js
> +export default new class BdWebApi {
maybe `SiteApi`/`WebsiteApi` or just `www`

2022-08-31 20:18 UTC, Tropix126 commented on renderer/src/ui/addonerrormodal.jsx
> +                <TabBar items={tabs.map(({id, name}) => ({value: id, name}))} value={selectedTab.id} onChange={value => this.switchToTab(value)} />
Most likely. Which ever is merged first I can deal with in the respective branch.

2022-08-31 20:27 UTC, Tropix126 commented on renderer/src/ui/settings.js
> +            title,
Done

2022-08-31 20:27 UTC, Tropix126 commented on renderer/src/modules/bdwebapi.js
> +export default new class BdWebApi {
Renamed to WebAPI.

2022-08-31 20:28 UTC, Tropix126 commented on renderer/src/styles/ui/markdown.css
> +
Accidental leftover from the now removed details pages. File is now deleted along with some other leftover dead styles from it.

2022-09-03 06:52 UTC, Strencher approved these changes
Looks good to me otherwise.

2022-09-03 06:52 UTC, Strencher commented on renderer/src/ui/settings/addonlist/store.jsx
> +    async install(id, filename) {
This could be converted to fully use `async` / `await` instead to make it more readable. Also, preferrably don't include the error itself in the toast as it makes it large & is not useful to the most users. Just log it into the console.
Example:
```js
// at the top
import {..., Logger} from "modules";

// later on...
async install(id, filename) {
	try {
		const contents = await WebAPI.getAddonContents(id);
		this.props.installAddon(contents,  filename);
	} catch (error) {
		Toasts.error(Strings.Store.downloadError.format({type: this.props.type}));
		Logger.err(`Failed to download ${filename}:`, error);
	}
}
```

2022-09-03 06:52 UTC, Strencher commented on renderer/src/ui/settings/addonlist/installed.jsx
> +    set: function() {Logger.warn("AddonList", "Addon policy for plugins #5 https://github.com/BetterDiscord/BetterDiscord/wiki/Addon-Policies#plugins");},
This message should be updated to <https://docs.betterdiscord.app/plugins/introduction/guidelines/#scope> (# 3)

2022-09-03 16:48 UTC, Tropix126 commented on renderer/src/builtins/addons/store.js
> +            return (embeds ?? []).concat(matchedProtocols.map((url) => {
Since `embeds` more or less comes from discord itself, and this effectively returns default behavior if there isn't a matched protocol, could this change the default behavior in any way as a side-effect (for example, if we returned `[]` every time and if discord did a null-check internally)?

2022-09-03 18:27 UTC, Tropix126 commented on renderer/src/ui/settings/addonlist/store.jsx
> +    async install(id, filename) {
Changed to `async`/`await` and removed verbose toast data. Logging is already handled by the respective modules.

2022-10-14 02:33 UTC, rauenzi approved these changes
The only thing I would change is having done a `git mv` of `renderer/src/ui/settings/addonlist.jsx` to `renderer/src/ui/settings/addonlist/installed.jsx` so the history and diff are maintained. Otherwise LGTM

2022-10-14 02:34 UTC, rauenzi commented
I will wait for Strencher to give a look over the latest review and we will probably move the target to the development branch

2023-02-09 22:01 UTC, Strencher requested changes

2024-02-26 01:08 UTC, rauenzi commented
@dav1312 who owns the rights to that image you posted https://github.com/BetterDiscord/BetterDiscord/pull/1193#issuecomment-1028953458 it looks great and would be cool to use for changelogs as you suggest.

Overall I'd like to salvage this code as much as I can. Once `v1.10.0` releases I might just make a branch and squash merge this into it and see if I can mash things together in a somewhat clean way since the codebase has made so many changes since this.

2024-11-11 08:54 UTC, Huderon commented
> @dav1312 who owns the rights to that image you posted https://github.com/BetterDiscord/BetterDiscord/pull/1193#issuecomment-1028953458 it looks great and would be cool to use for changelogs as you suggest.

It's Discord. The image that shows when there's no servers to display in server discovery. Nyria did the colouring, and I assume Dav added the title 

https://discord.com/assets/b92aabcc8b65fa979f9f.svg

2025-01-08 03:10 UTC, zerebos commented
Dropped in favor of #1796

2025-01-08 03:10 UTC, closed without merging