Refactor addon error modal
BetterDiscord/BetterDiscord pull request #1326
Opened 2022-06-27 23:38 UTC by Tropix126

2022-06-27 23:48 UTC, Tropix126 commented
If/when the store is merged I can bring over a common TabBar component that's accessible as well.

2022-08-04 17:25 UTC, rauenzi requested changes

2022-08-06 07:18 UTC, Tropix126 commented on renderer/src/ui/addonerrormodal.jsx
> +        const { err } = this.props;
Fixed in eda0175ed7b12add0623f96dd95e23ea0ee224ae

2022-08-06 07:21 UTC, Tropix126 commented on renderer/src/ui/addonerrormodal.jsx
> +const {ModalHeader, ModalContent} = WebpackModules.getByProps("ModalRoot");
aIs this necessarily any more breakable than the previous classes being used? I'd be happy to migrate these to their own components, but if I do that it might be a good idea to do this for the rest of the modals BD uses as well. I guess an obvious improvement here anyways would be to use the known `modals.js` module `ModalComponents` property rather than another webpack search.

2022-08-31 16:04 UTC, rauenzi commented on renderer/src/ui/addonerrormodal.jsx
> +const {ModalHeader, ModalContent} = WebpackModules.getByProps("ModalRoot");
We discussed this a bit in DMs

2022-08-31 16:06 UTC, rauenzi requested changes

2022-08-31 16:06 UTC, rauenzi commented on renderer/.pnpm-debug.log
> +{
Remove file

2022-08-31 16:06 UTC, rauenzi commented
Just remove the one file, otherwise LGTM

2024-02-26 01:09 UTC, rauenzi commented
Much like your other PR I will probably try to squash this into the current codebase after 1.10.0

2025-01-24 03:24 UTC, closed without merging