[Feature] Add uninject script
BetterDiscord/BetterDiscord pull request #1351
Opened 2022-08-01 19:42 UTC by TheGreenPig

Since it's possible to build and inject BD via npm scripts, but not remove/uninstall/uninject it, I thought this might be a nice addition for people with the manual install/developers.
I am not entirely sure if I have implemented it for all platforms correctly, I kind of just looked at how the installer uninstalls BD and tried to translate that logic here. Would be happy about suggestions/feedback.

I'm also not too sure if the naming "uninject" makes sense, but since the  "install" script refers to installing npm packages here and "inject" to actually injecting BD, "uninject" probably makes more sense than "uninstall" I think.

2022-08-01 20:05 UTC, Inve1951 commented on scripts/pathUtil.js
> +module.exports = function(useBdRelease, releaseInput, release, args) {
the export should be named
```suggestion
module.exports = {
  getDiscordPath
};

function getDiscordPath(useBdRelease, releaseInput, release, args) {
```

2022-08-02 18:46 UTC, TheGreenPig commented on scripts/pathUtil.js
> +module.exports = function(useBdRelease, releaseInput, release, args) {
Fixed (Amended commit)

2022-08-10 06:30 UTC, TheGreenPig commented
I wanted to switch my branch but sort of messed up... sorry please just ignore the opening and closing from above

2022-08-31 16:09 UTC, rauenzi requested changes

2022-08-31 16:09 UTC, rauenzi commented on scripts/pathUtil.js
> +function getDiscordPath(useBdRelease, releaseInput, release, args) {
For now let's just make this the default export and name the file something more specific than `pathUtil` and preferably all lowercase as well. `discordpath.js` would work fine.

2022-08-31 17:12 UTC, TheGreenPig commented on scripts/pathUtil.js
> +function getDiscordPath(useBdRelease, releaseInput, release, args) {
Applied changes in force push

2022-12-17 18:05 UTC, rauenzi commented
Welp... we have since changed injection method so.. this doesn't work haha

2023-04-17 18:58 UTC, rauenzi commented
Feel free to re-open if this gets updated.

2023-04-17 18:58 UTC, closed without merging