Fix header color in light mode
BetterDiscord/BetterDiscord pull request #1453
Opened 2022-10-18 20:08 UTC by FedeIlLeone

This PR fixes the header color of SettingsTitle. Since previously only white was used instead of the correct variable, the text was visible with a dark theme but not a light one.

Before -> After
![bef-aft](https://user-images.githubusercontent.com/38290480/196532730-75dc1b3d-b73b-4e9c-9e1e-ab63a54d9328.png)

2022-10-18 20:26 UTC, Strencher requested changes

2022-10-18 20:26 UTC, Strencher commented on renderer/src/styles/ui/bdsettings.css
> +    color: var(--header-primary);
Please add a fallback in case discord removes that css variable.

2022-10-19 19:09 UTC, FedeIlLeone commented on renderer/src/styles/ui/bdsettings.css
> +    color: var(--header-primary);
Now it should be fine, I set it to white by default in case that variable gets removed.

2023-04-17 19:16 UTC, rauenzi commented
Since there are three PRs (#1557 #1465 #1453) doing the same exact thing from three different people, I have decided to merge the one that came first. Sorry for any confusion or inconvenience!

2023-04-17 19:17 UTC, merged