Fix color of BD setting page titles
BetterDiscord/BetterDiscord pull request #1465
Opened 2022-10-24 19:29 UTC by j-f1

Before:

<img width="591" alt="Screenshot_2022-10-24 15 27 55" src="https://user-images.githubusercontent.com/25517624/197609405-b4726bde-82ed-4183-8988-6ec8c6682376.png">

After:
<img width="592" alt="Screenshot_2022-10-24 15 28 26" src="https://user-images.githubusercontent.com/25517624/197609486-c691b417-b818-4fc3-a130-1d18bc1aaec0.png">

2022-10-24 19:33 UTC, Strencher requested changes

2022-10-24 19:33 UTC, Strencher commented on renderer/src/styles/ui/bdsettings.css
> +    color: var(--header-primary, );
Please still provide a fallback.

2023-02-14 16:50 UTC, j-f1 commented on renderer/src/styles/ui/bdsettings.css
> +    color: var(--header-primary, );
Added! (sorry for the delay)

2023-04-17 19:17 UTC, rauenzi commented
Since there are three PRs (#1557 #1465 #1453) doing the same exact thing from three different people, I have decided to merge the one that came first. Sorry for any confusion or inconvenience!

2023-04-17 19:17 UTC, closed without merging