Fetch API
BetterDiscord/BetterDiscord pull request #1610
Opened 2023-04-12 21:51 UTC by Strencher

Adds `BdApi.fetch()` api which is equivalent design of the global `fetch()` api but it can bypass CSP. This also introduces the deprecation of `require("https")`/`require("request")` as well.

2023-04-13 00:54 UTC, rauenzi requested changes

2023-04-13 00:54 UTC, rauenzi commented on renderer/src/modules/api/index.js
> +BdApi.fetch = fetch;
I think we should think carefully about adding more to the base API object. We need to decide if we really want a namespace based structure.

2023-04-13 00:54 UTC, rauenzi commented on renderer/src/modules/api/fetch.js
> +export function fetch(url, options = {}) {
If this is going to be the only export in the file, why non-default? It diverts from the current norm of the codebase.

2023-04-13 00:54 UTC, rauenzi commented on preload/src/api/https.js
> +    } else {
```
}
else {
```

2023-04-13 00:54 UTC, rauenzi commented on preload/src/api/fetch.js
> +            } finally {
brace gets its own line

2023-04-13 00:54 UTC, rauenzi commented on preload/src/api/fetch.js
> +    execute(new URL(url), options);
Should any url validation/error handling be done here?

2023-04-13 00:54 UTC, rauenzi commented on preload/src/api/fetch.js
> +export function nativeFetch(url, options) {
Possible to create a JSDoc explaining the options here and in renderer?

2023-04-13 00:54 UTC, rauenzi commented on preload/src/api/fetch.js
> +            if (redirectCodes.has(res.statusCode) && res.headers.location && options.redirect !== "manual") {
Should a maxRedirects be added? Either configurable by API caller, or at least as a failsafe to prevent infinite redirects?

2023-04-13 00:54 UTC, rauenzi commented on renderer/src/modules/api/fetch.js
> +        });
Any way to clean this options object up a bit for clarity? This not easily human readable

2023-04-17 18:55 UTC, rauenzi commented
Could you also add the deprecation notices to the polyfill calls?

2023-04-30 14:16 UTC, Diegiwg approved these changes

2023-05-02 03:03 UTC, Diegiwg approved these changes

2023-05-02 03:47 UTC, rauenzi commented
@Diegiwg why?

2023-06-15 01:20 UTC, rauenzi approved these changes

2023-06-15 01:53 UTC, merged