Add ability to use native OS frame
BetterDiscord/BetterDiscord pull request #1709
Opened 2024-01-02 22:41 UTC by mahtaran

Enables the functionality to use native OS frame controls. If there is a reason why these were disabled, feel free to close this.

Fixes #1030.

2024-01-28 23:14 UTC, OneEyeTurner requested changes
So I went ahead and built all this out, and it works great!

The only thing that its missing is that this doesn't push the native frame to the pop out window of streams/video chats. That window still uses the original discord frame.

2024-02-29 00:13 UTC, mahtaran commented
> So I went ahead and built all this out, and it works great!
> 
> The only thing that its missing is that this doesn't push the native frame to the pop out window of streams/video chats. That window still uses the original discord frame.

Good catch @OneEyeTurner! Didn't think to check that. I just pushed some new changes which should make it so that any pop-out windows have the native frame if the option is turned on. It is done in a somewhat hacky fashion (never used Electron before) so if anyone knows a better solution, feel free to suggest changes.

@rauenzi Anything you'd like me to do before this can be merged?

2024-08-12 01:25 UTC, mahtaran commented
Closing this as there seems to be no further interest and I myself have moved over to Vencord.

2024-08-13 16:04 UTC, rauenzi commented
There is definitely interest as there is an outstanding feature request. I just have personally been very busy IRL as well as burnt out on client modding after 7-8 years.

2024-09-04 14:35 UTC, mahtaran commented
Alright, no worries! Take care and ping me whenever you have some more time, then I'll have a look at making sure it still works.

2025-01-06 12:27 UTC, closed without merging