Ability to inject to Discord Development builds.
BetterDiscord/BetterDiscord pull request #687
Opened 2021-04-11 10:15 UTC by dikahdoff

As mentioned here: #526
You can inject to the Dev builds with `npm run inject dev`

2021-06-21 06:47 UTC, geshii commented
It also fixes #843
But as I said in this issue, I don't know if adding it is a good idea since this client is just a canary clone and is deprecated.

2021-06-21 06:50 UTC, geshii requested changes

2021-06-21 06:50 UTC, geshii commented on README.md
> +1. Clone this repository `git clone https://github.com/dikahdoff/BetterDiscordApp.git`
```suggestion
1. Clone this repository `git clone https://github.com/rauenzi/BetterDiscordApp.git`
```
Why do you redirect to your own repo ??? I don't understand ?

2021-06-21 06:50 UTC, geshii commented on README.md
> +## Auto Installation
```suggestion
## Auto Installers
```
That was fine

2021-06-21 06:50 UTC, geshii commented on scripts/inject.js
> +const release = releaseInput === "canary" ? "Discord Canary" : releaseInput === "dev" ? "Discord Development" : releaseInput === "ptb" ? "Discord PTB" : "Discord";
```suggestion
const release = releaseInput === "canary" ? "Discord Canary" : releaseInput === "dev" ? "Discord Development" : releaseInput === "canary" ? "Discord PTB" : "Discord";
```
Discord dev is a clone of canary.

2021-06-23 18:33 UTC, NathanPeake commented
this would be nice to have since I use this version for testing with alts

2021-06-23 19:45 UTC, DonJTru commented on scripts/inject.js
> +const release = releaseInput === "canary" ? "Discord Canary" : releaseInput === "dev" ? "Discord Development" : "Discord";
Why remove PTB from injecting? you can just add "dev" as another switch, (see my comment on the pr)

2021-06-23 19:45 UTC, DonJTru commented on scripts/inject.js
> +const release = releaseInput === "canary" ? "Discord Canary" : releaseInput === "dev" ? "Discord Development" : releaseInput === "ptb" ? "Discord PTB" : "Discord";
Dev is a clone of canary, I do not understand the Suggested change though because ptb is in a separate file location.

2021-06-23 19:50 UTC, DonJTru commented
> 
> 
> It also fixes #843
> But as I said in this issue, I don't know if adding it is a good idea since this client is just a canary clone and is deprecated.

the API is deprecated but discord dev still gets pushed updates and has the feature to switch the API server from canary to stable via the .json file, IE: attached files being "canary.discord.com" and "cdn.discord.com" the old API allowed a "dev.discord.com" but they reused that sub-domain for developers.discord.com.

2021-06-24 05:36 UTC, geshii commented
@dikahdoff can you look at our requested changes?

2022-04-23 04:46 UTC, closed without merging