Rewrite AddonErrorModal/ErrorBoundary & Fix ChangelogModal Invite
BetterDiscord/BetterDiscord pull request #712
Opened 2021-04-17 22:54 UTC by Kyza

- Rewrote the AddonErrorModal fixing some bugs in it.
	- https://github.com/Kyza/BetterDiscordApp-1/blob/main/renderer/src/ui/addonerrormodal.jsx
- Rewrote the ErrorBoundary to be more useful.
	- https://github.com/Kyza/BetterDiscordApp-1/blob/main/renderer/src/ui/errorboundary.jsx
- Fixed the invite link in the changelog modal.
	- https://github.com/Kyza/BetterDiscordApp-1/blob/main/renderer/src/ui/modals.js#L269-L340

2021-05-07 00:29 UTC, rauenzi commented
What's with all the style/newline changes in `renderer/src/ui/modals.js`?

2021-05-07 03:56 UTC, Kyza commented
> What's with all the style/newline changes in `renderer/src/ui/modals.js`?

My formatter uses the default Prettier settings if there are no specific project-wide settings. That's why I highlighted the changes I made with the link in the OP. I can fix it by redoing those changes with my formatter off if you want.

2021-05-07 04:07 UTC, Kyza commented
> > What's with all the style/newline changes in `renderer/src/ui/modals.js`?
> 
> My formatter uses the default Prettier settings if there are no specific project-wide settings. That's why I highlighted the changes I made with the link in the OP. I can fix it by redoing those changes with my formatter off if you want.

Now that I look at it more that was caused by my formatter in https://github.com/rauenzi/BetterDiscordApp/pull/712/commits/c9aa24cb06f2ba13ed09b278d508bd016f5b9163, but is fixed later in https://github.com/rauenzi/BetterDiscordApp/pull/712/commits/4e14e43f4287dc1b2fd0329dbd70c74ab2ff1ec7. So the styling in the [final file](https://github.com/Kyza/BetterDiscordApp-1/blob/main/renderer/src/ui/modals.js) should be correct.

2021-06-05 18:26 UTC, rauenzi requested changes
In general there are _a lot_ of stylistic choices that stray from the norm for this codebase. Some of which I made comments on, some I haven't (there were too many to do on every single one). One I will mention here is the JSX style with every property being on it's own line even for smaller components.

2021-06-05 18:26 UTC, rauenzi commented on renderer/src/ui/addonerrormodal.jsx
> +const TabBarModule = WebpackModules.getModule(
Please keep this in tune with other queries, inline and no parentheses around a single parameter in an anonymous function

2021-06-05 18:26 UTC, rauenzi commented on assets/locales/en-us.json
>  {
Please eliminate the whitespace/indentation changes to this file

2021-06-05 18:26 UTC, rauenzi commented on renderer/src/ui/addonerrormodal.jsx
> +const detailsClasses = WebpackModules.getByProps(
Please make this a single-line query

2021-06-05 18:26 UTC, rauenzi commented on renderer/src/ui/addonerrormodal.jsx
> +            fallback={() => <Text>{Strings.Addons.errorLoadingErrors}</Text>}
Since `<Text>` comes from an internal webpack module and there's a chance of it not being there or not being found, does it make sense to use this as part of the error boundary's fallback?

2021-06-05 18:26 UTC, rauenzi commented on renderer/src/ui/addonerrormodal.jsx
> +                    {props.type === "plugins" ? <Extension /> : <ThemeIcon />}
Can you switch this check to be the opposite? There may be more addon types in the future, so it would be better to check if the addon type is `themes` and show the themes-specific icon, then for all other cases use the generic extension icon.

2021-06-05 18:26 UTC, rauenzi commented on renderer/src/ui/addonerrormodal.jsx
> +                            {content: props.error.stack, lang: "ruby"},
> ruby

Why?

2021-06-05 18:26 UTC, rauenzi commented on renderer/src/ui/errorboundary.jsx
> +            "https://raw.githubusercontent.com/facebook/react/master/scripts/error-codes/codes.json"
Are this error codes the same across all react versions? Would it make more sense to grab a specific version's set of codes rather than grab them from `master`?

2021-06-05 18:26 UTC, rauenzi commented on renderer/src/ui/errorboundary.jsx
> +            if (reactInvariants) {
This could be collapsed (66-81) if `getInvariants()` was the one managing the caching of the info so no checking is done here, it just calls the function and treats as a `Promise`

2021-06-05 18:26 UTC, rauenzi commented on renderer/src/ui/errorboundary.jsx
> +            "ErrorBoundary",
Why these newline changes?

2021-06-05 18:26 UTC, rauenzi commented on renderer/src/ui/icons/details.jsx
> +const detailsClasses = WebpackModules.getByProps(
single line this query

2021-06-05 18:26 UTC, rauenzi commented on renderer/src/ui/modals.js
>  import {Config} from "data";
This file has numerous style changes that we've already mentioned

2021-06-05 18:26 UTC, rauenzi commented on renderer/src/ui/modals.js
> +            !Changelog || !ModalStack || !ChangelogClasses || !TextElement || !FlexChild || !Titles || !MarkdownParser
why these newline and bracket changes?

2021-06-05 18:26 UTC, rauenzi commented on renderer/src/ui/modals.js
> +        const {
Again here

2021-06-05 18:26 UTC, rauenzi commented on renderer/src/ui/modals.js
> -            const supportLink = Anchor ? ce(Anchor, {onClick: joinSupportServer}, "Join our Discord Server.") : ce("a", {className: `${AnchorClasses.anchor} ${AnchorClasses.anchorUnderlineOnHover}`,
Why are these removed?

2021-06-05 18:26 UTC, rauenzi commented on renderer/src/ui/modals.js
> +                        renderFooter: renderFooter(props.onClose ?? (() => {})),
This line seems off. You removed the `return` of `renderFooter` above, yet you are calling the function here and using the return value (`undefined`) as the `renderFooter` prop instead of a function.

2021-06-05 23:29 UTC, Kyza commented on renderer/src/ui/addonerrormodal.jsx
> +            fallback={() => <Text>{Strings.Addons.errorLoadingErrors}</Text>}
The error boundary has a default fallback built in for if the fallback provided fails.

2021-06-05 23:34 UTC, Kyza commented on renderer/src/ui/modals.js
> +            !Changelog || !ModalStack || !ChangelogClasses || !TextElement || !FlexChild || !Titles || !MarkdownParser
I believe this is the default Prettier formatting preventing the line from being longer than 80(?) characters. I can revert this.

2021-06-05 23:43 UTC, Kyza commented on renderer/src/ui/errorboundary.jsx
> +            "https://raw.githubusercontent.com/facebook/react/master/scripts/error-codes/codes.json"
I don't think they break backwards compatibility, but I can see if I can grab the current version of React's errors and if not default to 16.

2022-08-31 16:01 UTC, rauenzi commented
Changes not made--closing.

2022-08-31 16:01 UTC, closed without merging